apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rfqw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rfqw
    app.kubernetes.io/part-of: byoc-app-ivbx
  name: rfqw
spec:
  rules:
  - host: rfqw-byoc-pexw-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-nlwwf.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: rfqw
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
